#!/usr/bin/env sh

########################################################
# script: ls
# description: shell util that replicates the ls command
# args: -a to show hidden files, -h to more information
# author: Marco T.
# e-mail: marcot.dns@gmail.com
########################################################


case "$1" in
    -a|--all)
        for content in ./* ./.*;do
            if [ "$content" = "." ] || [ "$content" == ".." ];then
                printf "%s\n" "$content"
            else
                content=${content#./}
                [ -d "$content" ] && printf "%s/\n" "$content" || printf "%s\n" "$content"
            fi
        done
        ;;

    -h|--help)
        printf 																\
            "shtools ls: 													\
            \n-a, --all: show all files, including hidden ones\n"	\
            ;;

    *)
        for content in ./*;do
            content=${content#./}
            [ -d "$content" ] && printf "%s/\n" "$content" || printf "%s\n" "$content"
        done
        ;;
esac
